//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/MapAlgorithm.java
//
//  Created by nziebart on 10/23/12.
//

void ComAqwertianFingeringMapAlgorithm_unused() {}
