//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/MusNotesFile.java
//
//  Created by nziebart on 10/23/12.
//

@class ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol JavaUtilCollection;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "MusNotesFile.h"
#import "MusicFile.h"
#import "java/lang/Enum.h"

@interface ComAqwertianFingeringMusNotesFile : ComAqwertianFingeringMusicFile {
 @public
  id<JavaUtilList> _elements_;
}

@property (nonatomic, strong) id<JavaUtilList> _elements;

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (int)getChannelCount;
- (id<JavaUtilList>)extractNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels;
- (void)storeWithJavaIoOutputStream:(JavaIoOutputStream *)o;
- (NSString *)description;
+ (void)storeWithJavaUtilList:(id<JavaUtilList>)notes
       withJavaIoOutputStream:(JavaIoOutputStream *)o;
@end

typedef enum {
  ComAqwertianFingeringMusNotesFile_MusElement_Type_PIECE = 0,
  ComAqwertianFingeringMusNotesFile_MusElement_Type_MEASURE = 1,
  ComAqwertianFingeringMusNotesFile_MusElement_Type_NOTE = 2,
  ComAqwertianFingeringMusNotesFile_MusElement_Type_MARK = 3,
} ComAqwertianFingeringMusNotesFile_MusElement_Type;

@interface ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum : JavaLangEnum < NSCopying > {
 @public
  NSString *prefix_;
}
@property (nonatomic, copy) NSString *prefix;

+ (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)PIECE;
+ (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)MEASURE;
+ (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)NOTE;
+ (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)MARK;
+ (IOSObjectArray *)values;
+ (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)prefix
          withNSString:(NSString *)name
               withInt:(int)ordinal;
- (NSString *)getPrefix;
+ (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)fromPrefixWithNSString:(NSString *)prefix;
@end

@protocol ComAqwertianFingeringMusNotesFile_MusElement < NSObject >
- (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)getType;
- (NSString *)getLine;
@end

@interface ComAqwertianFingeringMusNotesFile_BasicElement : NSObject < ComAqwertianFingeringMusNotesFile_MusElement > {
 @public
  ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *_type_;
  id<JavaUtilList> _words_;
}

@property (nonatomic, strong) ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *_type;
@property (nonatomic, strong) id<JavaUtilList> _words;

+ (id<ComAqwertianFingeringMusNotesFile_MusElement>)createWithNSString:(NSString *)line;
- (id)initWithNSString:(NSString *)line;
+ (id<JavaUtilList>)parseLineWithNSString:(NSString *)line;
+ (NSString *)composeLineWithJavaUtilList:(id<JavaUtilList>)words;
- (NSString *)getLine;
- (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)getType;
@end

@interface ComAqwertianFingeringMusNotesFile_MusPiece : ComAqwertianFingeringMusNotesFile_BasicElement {
}

- (id)initWithNSString:(NSString *)line;
@end

@interface ComAqwertianFingeringMusNotesFile_MusNote : ComAqwertianFingeringMusicFile_Note < ComAqwertianFingeringMusNotesFile_MusElement > {
 @public
  id<JavaUtilList> _words_;
}

@property (nonatomic, strong) id<JavaUtilList> _words;

- (id)initWithNSString:(NSString *)line;
- (NSString *)getLine;
- (ComAqwertianFingeringMusNotesFile_MusElement_TypeEnum *)getType;
- (BOOL)isTieNote;
- (void)adjustWords;
@end
