//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/MusPlayFile.java
//
//  Created by nziebart on 10/23/12.
//

@class ComAqwertianFingeringMusPlayFile_MusPlayNote;
@class ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration;
@class ComAqwertianFingeringStringTokenizer;
@class IOSObjectArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@class JavaIoPrintWriter;
@protocol JavaLangIterable;
@protocol JavaUtilCollection;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "MusicFile.h"
#import "java/lang/Comparable.h"
#import "java/util/Comparator.h"

#define ComAqwertianFingeringMusPlayFile_QUANTA_PER_MEASURE 200
#define ComAqwertianFingeringMusPlayFile_QUANTUM 4

@interface ComAqwertianFingeringMusPlayFile : ComAqwertianFingeringMusicFile {
 @public
  NSString *_name_;
  id<JavaUtilList> _events_;
  id<JavaUtilList> _repeats_;
}

@property (nonatomic, copy) NSString *_name;
@property (nonatomic, strong) id<JavaUtilList> _events;
@property (nonatomic, strong) id<JavaUtilList> _repeats;

+ (NSString *)INDENT;
- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (void)addNoteWithComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)note;
+ (void)setNoteDurationWithComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)note
                               withComAqwertianFingeringStringTokenizer:(ComAqwertianFingeringStringTokenizer *)tok;
+ (int)getNoteWithNSString:(NSString *)cmd
withComAqwertianFingeringStringTokenizer:(ComAqwertianFingeringStringTokenizer *)tok;
+ (int)calcNoteWithNSString:(NSString *)cmd
               withNSString:(NSString *)note
                    withInt:(int)base
withComAqwertianFingeringStringTokenizer:(ComAqwertianFingeringStringTokenizer *)tok;
+ (int)calcOctaveWithInt:(int)base
                 withInt:(int)octave;
+ (IOSObjectArray *)TONE;
+ (NSString *)calcMusPlayToneWithInt:(int)note;
+ (int)calcMusPlayOctaveWithInt:(int)note;
+ (void)resetDurationWithComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)note;
- (int)getChannelCount;
- (id<JavaUtilList>)extractNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels;
- (void)processRepeats;
- (void)storeWithJavaIoOutputStream:(JavaIoOutputStream *)o;
+ (void)processMetaInfoWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)prev
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)n;
+ (void)processMeasureWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)prev
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)n;
+ (void)processLineWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)prev
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)n;
+ (void)processVolumeWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)prev
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)n;
+ (void)processNoteWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)prev
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)n;
+ (void)outputNoteWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)n;
+ (void)outputDurationWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg
withComAqwertianFingeringMusPlayFile_MusPlayNote_Duration:(ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration *)d;
+ (void)outputBeatsWithJavaIoPrintWriter:(JavaIoPrintWriter *)outArg
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)prev;
+ (NSString *)toMusPlayNoteWithInt:(int)note;
- (NSString *)description;
+ (void)storeNotesWithNSString:(NSString *)songName
              withJavaUtilList:(id<JavaUtilList>)notes
        withJavaIoOutputStream:(JavaIoOutputStream *)o;
+ (void)storeMusPlayNotesWithNSString:(NSString *)songName
                     withJavaUtilList:(id<JavaUtilList>)notes
               withJavaIoOutputStream:(JavaIoOutputStream *)o;
+ (id<JavaUtilList>)convertToMusPlayWithJavaLangIterable:(id<JavaLangIterable>)notes;
+ (id<JavaUtilList>)placeNotesInMeasuresWithJavaLangIterable:(id<JavaLangIterable>)notes;
+ (int)calcMeasureWithInt:(int)time;
+ (void)addNoteToMeasureWithJavaUtilList:(id<JavaUtilList>)notesByMeasure
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)note
                                 withInt:(int)measure;
+ (void)placeNoteInLineWithJavaUtilList:(id<JavaUtilList>)notesInMeasure
withComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)note;
+ (NSString *)buildLineWithInt:(int)lineNumber;
+ (ComAqwertianFingeringMusPlayFile_MusPlayNote *)toMusPlayNoteWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n
                                                                                               withInt:(int)maxVolume;
+ (id<JavaUtilList>)extractAndSortNotesWithJavaUtilList:(id<JavaUtilList>)notesByMeasure;
+ (void)insertRestsWithJavaUtilList:(id<JavaUtilList>)notes;
+ (int)findMaxVolumeWithJavaLangIterable:(id<JavaLangIterable>)notes;
@end

@interface ComAqwertianFingeringMusPlayFile_MusPlayNote : ComAqwertianFingeringMusicFile_Note < NSCopying > {
 @public
  ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration *meter_;
  NSString *key_;
  NSString *tempo_;
  int measure_;
  NSString *line_;
  ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration *length_;
  int sequence_;
}

@property (nonatomic, strong) ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration *meter;
@property (nonatomic, copy) NSString *key;
@property (nonatomic, copy) NSString *tempo;
@property (nonatomic, assign) int measure;
@property (nonatomic, copy) NSString *line;
@property (nonatomic, strong) ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration *length;
@property (nonatomic, assign) int sequence;

- (id)init;
- (id)initWithComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)previous;
- (id)clone;
- (NSString *)description;
- (int)compareToWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)note;
- (void)addDurationWithComAqwertianFingeringMusPlayFile_MusPlayNote:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)toAdd;
- (id)copyWithZone:(NSZone *)zone;
@end

@interface ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration : NSObject < JavaLangComparable, NSCopying > {
 @public
  int num_;
  int denom_;
  int divisor_;
  BOOL reducable_;
}

@property (nonatomic, assign) int num;
@property (nonatomic, assign) int denom;
@property (nonatomic, assign) int divisor;
@property (nonatomic, assign) BOOL reducable;

- (id)init;
- (id)initWithBOOL:(BOOL)reducable;
- (void)addWithComAqwertianFingeringMusPlayFile_MusPlayNote_Duration:(ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration *)toAdd;
- (void)subtractWithComAqwertianFingeringMusPlayFile_MusPlayNote_Duration:(ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration *)toSub;
- (int)compareToWithId:(ComAqwertianFingeringMusPlayFile_MusPlayNote_Duration *)toComp;
- (BOOL)isEqual:(id)o;
- (id)clone;
- (void)reduce;
- (NSString *)description;
- (id)copyWithZone:(NSZone *)zone;
@end

@interface ComAqwertianFingeringMusPlayFile_Repeat : NSObject {
 @public
  int start_;
  int end_;
  int repeat_at_;
}

@property (nonatomic, assign) int start;
@property (nonatomic, assign) int end;
@property (nonatomic, assign) int repeat_at;

@end

@interface ComAqwertianFingeringMusPlayFile_$1 : NSObject < JavaUtilComparator > {
}

- (int)compareWithId:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)n1
              withId:(ComAqwertianFingeringMusPlayFile_MusPlayNote *)n2;
@end
