//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/QwertyMapper.java
//
//  Created by nziebart on 10/23/12.
//

#import "IOSObjectArray.h"
#import "MapAlgorithm.h"
#import "MusicFile.h"
#import "PatternList.h"
#import "QwertyMapper.h"
#import "RandomAlgorithm.h"
#import "RoundRobinAlgorithm.h"
#import "UsageAlgorithm.h"
#import "java/lang/IllegalArgumentException.h"
#import "java/lang/Integer.h"
#import "java/lang/NullPointerException.h"
#import "java/util/Collection.h"
#import "java/util/Iterator.h"
#import "java/util/LinkedList.h"
#import "java/util/Map.h"
#import "java/util/Random.h"
#import "java/util/Set.h"
#import "java/util/TreeMap.h"

@implementation ComAqwertianFingeringQwertyMapper

static IOSObjectArray * ComAqwertianFingeringQwertyMapper_FINGER_;

- (id<ComAqwertianFingeringMapAlgorithm>)_algo {
  return _algo_;
}

- (void)set_algo:(id<ComAqwertianFingeringMapAlgorithm>)new_algo {
  _algo_ = new_algo;
}

- (id<JavaUtilMap>)_noteHist {
  return _noteHist_;
}

- (void)set_noteHist:(id<JavaUtilMap>)new_noteHist {
  _noteHist_ = new_noteHist;
}

- (JavaUtilRandom *)rand {
  return rand_;
}

- (void)setRand:(JavaUtilRandom *)newRand {
  rand_ = newRand;
}


+ (IOSObjectArray *)FINGER {
  return ComAqwertianFingeringQwertyMapper_FINGER_;
}

+ (unichar)FINGER_START {
  return ComAqwertianFingeringQwertyMapper_FINGER_START;
}

- (id)initWithComAqwertianFingeringQwertyMapper_AlgorithmEnum:(ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)algorithm
  withComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:(ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)level
                                           withJavaUtilRandom:(JavaUtilRandom *)rand {
  if ((self = [super init])) {
    _noteHist_ = [[JavaUtilTreeMap alloc] init];
    self.rand = rand;
    switch ([algorithm ordinal]) {
      case ComAqwertianFingeringQwertyMapper_Algorithm_RANDOM:
      _algo_ = [[ComAqwertianFingeringRandomAlgorithm alloc] initWithComAqwertianFingeringQwertyMapper:self];
      break;
      case ComAqwertianFingeringQwertyMapper_Algorithm_ROUND_ROBIN:
      _algo_ = [[ComAqwertianFingeringRoundRobinAlgorithm alloc] initWithComAqwertianFingeringQwertyMapper:self];
      break;
      case ComAqwertianFingeringQwertyMapper_Algorithm_USAGE:
      _algo_ = [[ComAqwertianFingeringUsageAlgorithm alloc] initWithComAqwertianFingeringQwertyMapper:self withComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:level];
      break;
      default:
      @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:[NSString stringWithFormat:@"Unrecognized algorithm: %@", algorithm]];
    }
  }
  return self;
}

- (id)initWithComAqwertianFingeringQwertyMapper_AlgorithmEnum:(ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)algorithm
  withComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:(ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)level {
  return [self initWithComAqwertianFingeringQwertyMapper_AlgorithmEnum:algorithm withComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:level withJavaUtilRandom:[[JavaUtilRandom alloc] init]];
}

- (NSString *)getInfo {
  return [((id<ComAqwertianFingeringMapAlgorithm>) NIL_CHK(_algo_)) getInfo];
}

- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)notes
withComAqwertianFingeringPatternList:(ComAqwertianFingeringPatternList *)patterns {
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) notes;
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      ComAqwertianFingeringMusicFile_Note * n = (ComAqwertianFingeringMusicFile_Note *) [iter__ next];
      [self addToHistogramWithJavaUtilMap:_noteHist_ withNSString:[((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)) getNoteValue]];
    }
  }
  [((id<ComAqwertianFingeringMapAlgorithm>) NIL_CHK(_algo_)) mapWithJavaUtilCollection:notes withComAqwertianFingeringPatternList:patterns withJavaUtilMap:_noteHist_];
}

+ (unichar)getHandWithInt:(int)qwerty {
  return [[((IOSObjectArray *) NIL_CHK(ComAqwertianFingeringQwertyMapper_FINGER_)) objectAtIndex:qwerty - ComAqwertianFingeringQwertyMapper_FINGER_START] charAtWithInt:0];
}

+ (NSString *)getFingerWithInt:(int)qwerty {
  return [[((IOSObjectArray *) NIL_CHK(ComAqwertianFingeringQwertyMapper_FINGER_)) objectAtIndex:qwerty - ComAqwertianFingeringQwertyMapper_FINGER_START] substring:0 endIndex:2];
}

+ (int)getRowWithInt:(int)qwerty {
  return [[((IOSObjectArray *) NIL_CHK(ComAqwertianFingeringQwertyMapper_FINGER_)) objectAtIndex:qwerty - ComAqwertianFingeringQwertyMapper_FINGER_START] charAtWithInt:2] - '0';
}

+ (unichar)getQwertyWithNSString:(NSString *)finger
                         withInt:(int)row {
  NSString *f = [NSString stringWithFormat:@"%@%d", finger, row];
  for (int i = 0; i < (int) [((IOSObjectArray *) NIL_CHK(ComAqwertianFingeringQwertyMapper_FINGER_)) count]; i++) if ([[((IOSObjectArray *) NIL_CHK(ComAqwertianFingeringQwertyMapper_FINGER_)) objectAtIndex:i] isEqual:f]) return (unichar) (i + ComAqwertianFingeringQwertyMapper_FINGER_START);
  return 0;
}

+ (unichar)getKeyWithInt:(int)index {
  return (unichar) (ComAqwertianFingeringQwertyMapper_FINGER_START + index);
}

+ (int)getIndexWithUnichar:(unichar)key {
  return (key - ComAqwertianFingeringQwertyMapper_FINGER_START);
}

- (ComAqwertianFingeringQwertyMapper_KeyHistory *)createKeyHistory {
  return [[ComAqwertianFingeringQwertyMapper_KeyHistory alloc] init];
}

- (BOOL)ruleFailsWithComAqwertianFingeringQwertyMapper_KeyHistory:(ComAqwertianFingeringQwertyMapper_KeyHistory *)history
                          withComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)currNote
                                                      withUnichar:(unichar)key {
  ComAqwertianFingeringMusicFile_Note *prevNote = [((ComAqwertianFingeringQwertyMapper_KeyHistory *) NIL_CHK(history)) getPrevious];
  if (prevNote == nil) return NO;
  if (((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(prevNote)).qwerty == key && ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(prevNote)).note == ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(currNote)).note) return NO;
  NSString *prevFinger = [ComAqwertianFingeringQwertyMapper getFingerWithInt:((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(prevNote)).qwerty];
  NSString *nextFinger = [ComAqwertianFingeringQwertyMapper getFingerWithInt:key];
  if ([self isImpossibleFingerWithNSString:prevFinger withNSString:nextFinger]) return YES;
  if ([((ComAqwertianFingeringQwertyMapper_KeyHistory *) NIL_CHK(history)) isFingerDownWithNSString:nextFinger]) return YES;
  return NO;
}

- (BOOL)isImpossibleFingerWithNSString:(NSString *)prevFinger
                          withNSString:(NSString *)nextFinger {
  if ([NIL_CHK(prevFinger) charAtWithInt:0] != [NIL_CHK(nextFinger) charAtWithInt:0]) return NO;
  if ([NIL_CHK(prevFinger) charAtWithInt:1] == [NIL_CHK(nextFinger) charAtWithInt:1]) return YES;
  switch ([NIL_CHK(prevFinger) charAtWithInt:1]) {
    case '1':
    return ([NIL_CHK(nextFinger) charAtWithInt:1] == '2');
    case '2':
    return ([NIL_CHK(nextFinger) charAtWithInt:1] == '1' || [NIL_CHK(nextFinger) charAtWithInt:1] == '3');
    case '3':
    return ([NIL_CHK(nextFinger) charAtWithInt:1] == '2' || [NIL_CHK(nextFinger) charAtWithInt:1] == '4');
    case '4':
    return ([NIL_CHK(nextFinger) charAtWithInt:1] == '3');
  }
  return NO;
}

- (NSString *)toStringWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n {
  NSString *s = [((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)) description];
  s = [NSString stringWithFormat:@"%@%@", s, [NSString stringWithFormat:@"(%d)", ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).note]];
  s = [NSString stringWithFormat:@"%@%@", s, [NSString stringWithFormat:@" - %c/%@ %d", ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty, [ComAqwertianFingeringQwertyMapper getFingerWithInt:((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty], [ComAqwertianFingeringQwertyMapper getRowWithInt:((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty]]];
  if (((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).reason != nil) s = [NSString stringWithFormat:@"%@%@", s, [NSString stringWithFormat:@". Reason: %@", ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).reason]];
  return s;
}

- (void)addToHistogramWithJavaUtilMap:(id<JavaUtilMap>)hist
                         withNSString:(NSString *)key {
  int count = 0;
  if ([((id<JavaUtilMap>) NIL_CHK(hist)) containsKeyWithId:key]) count = [((JavaLangInteger *) [((id<JavaUtilMap>) NIL_CHK(hist)) getWithId:key]) intValue];
  count++;
  [((id<JavaUtilMap>) NIL_CHK(hist)) putWithId:key withId:[JavaLangInteger valueOfWithInt:count]];
}

- (void)printStatisticsWithJavaUtilCollection:(id<JavaUtilCollection>)notes {
  [self printHistogramWithJavaUtilMap:_noteHist_ withNSString:@"Histogram of Notes"];
  NSLog(@"");
  id<JavaUtilMap> qwertyHist = [[JavaUtilTreeMap alloc] init];
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) notes;
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      ComAqwertianFingeringMusicFile_Note * n = (ComAqwertianFingeringMusicFile_Note *) [iter__ next];
      [self addToHistogramWithJavaUtilMap:qwertyHist withNSString:[NSString valueOfChar:((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty]];
    }
  }
  [self printHistogramWithJavaUtilMap:qwertyHist withNSString:@"Histogram of Key Usage"];
  NSLog(@"");
  qwertyHist = [[JavaUtilTreeMap alloc] init];
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) notes;
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      ComAqwertianFingeringMusicFile_Note * n = (ComAqwertianFingeringMusicFile_Note *) [iter__ next];
      [self addToHistogramWithJavaUtilMap:qwertyHist withNSString:[ComAqwertianFingeringQwertyMapper getFingerWithInt:((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty]];
    }
  }
  [self printHistogramWithJavaUtilMap:qwertyHist withNSString:@"Histogram of Finger Usage"];
  NSLog(@"");
  qwertyHist = [[JavaUtilTreeMap alloc] init];
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) notes;
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      ComAqwertianFingeringMusicFile_Note * n = (ComAqwertianFingeringMusicFile_Note *) [iter__ next];
      [self addToHistogramWithJavaUtilMap:qwertyHist withNSString:[NSString valueOfInt:[ComAqwertianFingeringQwertyMapper getRowWithInt:((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty]]];
    }
  }
  [self printHistogramWithJavaUtilMap:qwertyHist withNSString:@"Histogram of Row Usage"];
}

- (void)printHistogramWithJavaUtilMap:(id<JavaUtilMap>)hist
                         withNSString:(NSString *)title {
  NSLog(@"%@", title);
  int total = 0;
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) [((id<JavaUtilMap>) NIL_CHK(hist)) keySet];
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      NSString * key = (NSString *) [iter__ next];
      int count = [((JavaLangInteger *) [((id<JavaUtilMap>) NIL_CHK(hist)) getWithId:key]) intValue];
      total += count;
      NSLog(@"%@", [NSString stringWithFormat:@"%@: %d", key, count]);
    }
  }
  NSLog(@"%@", [NSString stringWithFormat:@"%d bins, %d values.", [((id<JavaUtilMap>) NIL_CHK(hist)) size], total]);
}

+ (void)initialize {
  if (self == [ComAqwertianFingeringQwertyMapper class]) {
    ComAqwertianFingeringQwertyMapper_FINGER_ = [IOSObjectArray arrayWithObjects:(id[]){ @"R00", @"", @"", @"", @"", @"", @"", @"", @"", @"", @"", @"", @"R21", @"", @"R31", @"R41", @"R44", @"L44", @"L34", @"L24", @"L14", @"L14", @"R14", @"R14", @"R24", @"R34", @"", @"R42", @"", @"", @"", @"", @"", @"L42", @"L11", @"L21", @"L22", @"L23", @"L12", @"L12", @"R12", @"R23", @"R12", @"R22", @"R32", @"R11", @"R11", @"R33", @"R43", @"L43", @"L13", @"L32", @"L13", @"R13", @"L11", @"L33", @"L31", @"R13", @"L41" } count:59 type:[IOSClass classWithClass:[NSString class]]];
  }
}

@end


static ComAqwertianFingeringQwertyMapper_AlgorithmEnum *ComAqwertianFingeringQwertyMapper_AlgorithmEnum_RANDOM;
static ComAqwertianFingeringQwertyMapper_AlgorithmEnum *ComAqwertianFingeringQwertyMapper_AlgorithmEnum_ROUND_ROBIN;
static ComAqwertianFingeringQwertyMapper_AlgorithmEnum *ComAqwertianFingeringQwertyMapper_AlgorithmEnum_USAGE;
IOSObjectArray *ComAqwertianFingeringQwertyMapper_AlgorithmEnum_values;

@implementation ComAqwertianFingeringQwertyMapper_AlgorithmEnum

+ (ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)RANDOM {
  return ComAqwertianFingeringQwertyMapper_AlgorithmEnum_RANDOM;
}
+ (ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)ROUND_ROBIN {
  return ComAqwertianFingeringQwertyMapper_AlgorithmEnum_ROUND_ROBIN;
}
+ (ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)USAGE {
  return ComAqwertianFingeringQwertyMapper_AlgorithmEnum_USAGE;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

- (id)initWithNSString:(NSString *)name withInt:(int)ordinal {
  return [super initWithNSString:name withInt:ordinal];
}

+ (void)initialize {
  if (self == [ComAqwertianFingeringQwertyMapper_AlgorithmEnum class]) {
    ComAqwertianFingeringQwertyMapper_AlgorithmEnum_RANDOM = [[ComAqwertianFingeringQwertyMapper_AlgorithmEnum alloc] initWithNSString:@"RANDOM" withInt:0];
    ComAqwertianFingeringQwertyMapper_AlgorithmEnum_ROUND_ROBIN = [[ComAqwertianFingeringQwertyMapper_AlgorithmEnum alloc] initWithNSString:@"ROUND_ROBIN" withInt:1];
    ComAqwertianFingeringQwertyMapper_AlgorithmEnum_USAGE = [[ComAqwertianFingeringQwertyMapper_AlgorithmEnum alloc] initWithNSString:@"USAGE" withInt:2];
    ComAqwertianFingeringQwertyMapper_AlgorithmEnum_values = [[IOSObjectArray alloc] initWithObjects:(id[]){ ComAqwertianFingeringQwertyMapper_AlgorithmEnum_RANDOM, ComAqwertianFingeringQwertyMapper_AlgorithmEnum_ROUND_ROBIN, ComAqwertianFingeringQwertyMapper_AlgorithmEnum_USAGE, nil } count:3 type:[IOSClass classWithClass:[ComAqwertianFingeringQwertyMapper_AlgorithmEnum class]]];
  }
}

+ (IOSObjectArray *)values {
  return [IOSObjectArray arrayWithArray:ComAqwertianFingeringQwertyMapper_AlgorithmEnum_values];
}

+ (ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)valueOfWithNSString:(NSString *)name {
  for (int i = 0; i < [ComAqwertianFingeringQwertyMapper_AlgorithmEnum_values count]; i++) {
    ComAqwertianFingeringQwertyMapper_AlgorithmEnum *e = [ComAqwertianFingeringQwertyMapper_AlgorithmEnum_values objectAtIndex:i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

@end
static ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_BEGINNER;
static ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_INTERMEDIATE;
static ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_ADVANCED;
static ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_EXPERT;
IOSObjectArray *ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_values;

@implementation ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum

+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)BEGINNER {
  return ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_BEGINNER;
}
+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)INTERMEDIATE {
  return ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_INTERMEDIATE;
}
+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)ADVANCED {
  return ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_ADVANCED;
}
+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)EXPERT {
  return ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_EXPERT;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

- (id)initWithNSString:(NSString *)name withInt:(int)ordinal {
  return [super initWithNSString:name withInt:ordinal];
}

+ (void)initialize {
  if (self == [ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum class]) {
    ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_BEGINNER = [[ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum alloc] initWithNSString:@"BEGINNER" withInt:0];
    ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_INTERMEDIATE = [[ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum alloc] initWithNSString:@"INTERMEDIATE" withInt:1];
    ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_ADVANCED = [[ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum alloc] initWithNSString:@"ADVANCED" withInt:2];
    ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_EXPERT = [[ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum alloc] initWithNSString:@"EXPERT" withInt:3];
    ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_values = [[IOSObjectArray alloc] initWithObjects:(id[]){ ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_BEGINNER, ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_INTERMEDIATE, ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_ADVANCED, ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_EXPERT, nil } count:4 type:[IOSClass classWithClass:[ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum class]]];
  }
}

+ (IOSObjectArray *)values {
  return [IOSObjectArray arrayWithArray:ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_values];
}

+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)valueOfWithNSString:(NSString *)name {
  for (int i = 0; i < [ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_values count]; i++) {
    ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *e = [ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum_values objectAtIndex:i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

@end
@implementation ComAqwertianFingeringQwertyMapper_KeyHistory

- (JavaUtilLinkedList *)_mapped {
  return _mapped_;
}

- (void)set_mapped:(JavaUtilLinkedList *)new_mapped {
  _mapped_ = new_mapped;
}

- (JavaUtilLinkedList *)_playing {
  return _playing_;
}

- (void)set_playing:(JavaUtilLinkedList *)new_playing {
  _playing_ = new_playing;
}


- (id)init {
  if ((self = [super init])) {
    _mapped_ = [[JavaUtilLinkedList alloc] init];
    _playing_ = [[JavaUtilLinkedList alloc] init];
  }
  return self;
}

- (void)addNoteWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n {
  [((JavaUtilLinkedList *) NIL_CHK(_mapped_)) addFirstWithId:n];
  if ([((JavaUtilLinkedList *) NIL_CHK(_mapped_)) size] > ComAqwertianFingeringQwertyMapper_USAGE_LIMIT) [((JavaUtilLinkedList *) NIL_CHK(_mapped_)) removeLast];
  int currTime = ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).time;
  for (id<JavaUtilIterator> it = ((id<JavaUtilIterator>) [((JavaUtilLinkedList *) NIL_CHK(_playing_)) iterator]); [((id<JavaUtilIterator>) NIL_CHK(it)) hasNext]; ) {
    ComAqwertianFingeringMusicFile_Note *note = ((ComAqwertianFingeringMusicFile_Note *) [((id<JavaUtilIterator>) NIL_CHK(it)) next]);
    int noteOffTime = ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(note)).time + ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(note)).duration;
    if (noteOffTime <= currTime) [((id<JavaUtilIterator>) NIL_CHK(it)) remove];
  }
  [((JavaUtilLinkedList *) NIL_CHK(_playing_)) addLastWithId:n];
}

- (ComAqwertianFingeringMusicFile_Note *)getPrevious {
  if ([((JavaUtilLinkedList *) NIL_CHK(_mapped_)) size] == 0) return nil;
  return ((ComAqwertianFingeringMusicFile_Note *) [((JavaUtilLinkedList *) NIL_CHK(_mapped_)) getWithInt:0]);
}

- (ComAqwertianFingeringMusicFile_Note *)findMappedNoteWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n {
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) _mapped_;
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      ComAqwertianFingeringMusicFile_Note * used = (ComAqwertianFingeringMusicFile_Note *) [iter__ next];
      if (((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(used)).note == ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).note) return used;
    }
  }
  return nil;
}

- (BOOL)isPlayingWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)note {
  return [((JavaUtilLinkedList *) NIL_CHK(_playing_)) containsWithId:note];
}

- (BOOL)isFingerDownWithNSString:(NSString *)nextFinger {
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) _playing_;
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      ComAqwertianFingeringMusicFile_Note * n = (ComAqwertianFingeringMusicFile_Note *) [iter__ next];
      NSString *finger = [ComAqwertianFingeringQwertyMapper getFingerWithInt:((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty];
      if ([NIL_CHK(nextFinger) isEqual:finger]) return YES;
    }
  }
  return NO;
}

@end


