//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/RandomAlgorithm.java
//
//  Created by nziebart on 10/23/12.
//

#import "IOSObjectArray.h"
#import "MusicFile.h"
#import "PatternList.h"
#import "QwertyMapper.h"
#import "RandomAlgorithm.h"
#import "java/lang/NullPointerException.h"
#import "java/util/Collection.h"
#import "java/util/Iterator.h"
#import "java/util/Map.h"
#import "java/util/Random.h"

@implementation ComAqwertianFingeringRandomAlgorithm

- (JavaUtilRandom *)rand {
  return rand_;
}

- (void)setRand:(JavaUtilRandom *)newRand {
  rand_ = newRand;
}


- (id)initWithComAqwertianFingeringQwertyMapper:(ComAqwertianFingeringQwertyMapper *)m {
  if ((self = [super init])) {
    rand_ = [[JavaUtilRandom alloc] init];
  }
  return self;
}

- (NSString *)getInfo {
  return @"Random key assignment.";
}

- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)notes
withComAqwertianFingeringPatternList:(ComAqwertianFingeringPatternList *)patterns
                  withJavaUtilMap:(id<JavaUtilMap>)notesHistogram {
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) notes;
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      ComAqwertianFingeringMusicFile_Note * n = (ComAqwertianFingeringMusicFile_Note *) [iter__ next];
      int q;
      do {
        q = [((JavaUtilRandom *) NIL_CHK(rand_)) nextIntWithInt:(int) [((IOSObjectArray *) NIL_CHK([ComAqwertianFingeringQwertyMapper FINGER])) count]];
      }
      while ([[((IOSObjectArray *) NIL_CHK([ComAqwertianFingeringQwertyMapper FINGER])) objectAtIndex:q] length] == 0);
      ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty = (unichar) (ComAqwertianFingeringQwertyMapper_FINGER_START + q);
    }
  }
}

@end


