//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/RoundRobinAlgorithm.java
//
//  Created by nziebart on 10/23/12.
//

#import "IOSIntArray.h"
#import "IOSObjectArray.h"
#import "MusicFile.h"
#import "PatternList.h"
#import "QwertyMapper.h"
#import "RoundRobinAlgorithm.h"
#import "java/lang/NullPointerException.h"
#import "java/util/Collection.h"
#import "java/util/Iterator.h"
#import "java/util/Map.h"

@implementation ComAqwertianFingeringRoundRobinAlgorithm

static IOSObjectArray * ComAqwertianFingeringRoundRobinAlgorithm_FINGERS_;
static IOSIntArray * ComAqwertianFingeringRoundRobinAlgorithm_ROWS_;

- (ComAqwertianFingeringQwertyMapper *)_mapper {
  return _mapper_;
}

- (void)set_mapper:(ComAqwertianFingeringQwertyMapper *)new_mapper {
  _mapper_ = new_mapper;
}


- (id)initWithComAqwertianFingeringQwertyMapper:(ComAqwertianFingeringQwertyMapper *)m {
  if ((self = [super init])) {
    _mapper_ = m;
  }
  return self;
}

- (NSString *)getInfo {
  return @"Round robin finger assignment, round robin row.";
}

+ (IOSObjectArray *)FINGERS {
  return ComAqwertianFingeringRoundRobinAlgorithm_FINGERS_;
}

+ (IOSIntArray *)ROWS {
  return ComAqwertianFingeringRoundRobinAlgorithm_ROWS_;
}

- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)notes
withComAqwertianFingeringPatternList:(ComAqwertianFingeringPatternList *)patterns
                  withJavaUtilMap:(id<JavaUtilMap>)notesHistogram {
  int finger = 0;
  int row = 0;
  {
    id<JavaLangIterable> array__ = (id<JavaLangIterable>) notes;
    if (!array__) {
      @throw [[JavaLangNullPointerException alloc] init];
    }
    id<JavaUtilIterator> iter__ = [array__ iterator];
    while ([iter__ hasNext]) {
      ComAqwertianFingeringMusicFile_Note * n = (ComAqwertianFingeringMusicFile_Note *) [iter__ next];
      NSString *f = [((IOSObjectArray *) NIL_CHK(ComAqwertianFingeringRoundRobinAlgorithm_FINGERS_)) objectAtIndex:finger];
      if (++finger >= (int) [((IOSObjectArray *) NIL_CHK(ComAqwertianFingeringRoundRobinAlgorithm_FINGERS_)) count]) finger = 0;
      if ([NIL_CHK(f) isEqual:@"T0"]) ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty = [ComAqwertianFingeringQwertyMapper getQwertyWithNSString:f withInt:0];
      else {
        do {
          ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty = [ComAqwertianFingeringQwertyMapper getQwertyWithNSString:f withInt:[((IOSIntArray *) NIL_CHK(ComAqwertianFingeringRoundRobinAlgorithm_ROWS_)) intAtIndex:row]];
          if (++row >= (int) [((IOSIntArray *) NIL_CHK(ComAqwertianFingeringRoundRobinAlgorithm_ROWS_)) count]) row = 0;
        }
        while (((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).qwerty == 0);
      }
    }
  }
}

+ (void)initialize {
  if (self == [ComAqwertianFingeringRoundRobinAlgorithm class]) {
    ComAqwertianFingeringRoundRobinAlgorithm_FINGERS_ = [IOSObjectArray arrayWithObjects:(id[]){ @"L1", @"R1", @"L2", @"R2", @"L3", @"R3", @"L4", @"R4", @"T0" } count:9 type:[IOSClass classWithClass:[NSString class]]];
    ComAqwertianFingeringRoundRobinAlgorithm_ROWS_ = [IOSIntArray arrayWithInts:(int[]){ 1, 2, 3, 4, 3, 2 } count:6];
  }
}

@end


