//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/UsageAlgorithm.java
//
//  Created by nziebart on 10/23/12.
//

@class ComAqwertianFingeringMusicFile_Note;
@class ComAqwertianFingeringPatternList;
@class ComAqwertianFingeringQwertyMapper;
@class ComAqwertianFingeringQwertyMapper_KeyHistory;
@class ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum;
@class ComAqwertianFingeringUsageAlgorithm_ChordFinger;
@class ComAqwertianFingeringUsageAlgorithm_NextKey;
@class IOSCharArray;
@class IOSIntArray;
@class IOSObjectArray;
@protocol JavaUtilCollection;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "MapAlgorithm.h"
#import "PatternList.h"
#import "java/util/Comparator.h"

@interface ComAqwertianFingeringUsageAlgorithm : NSObject < ComAqwertianFingeringMapAlgorithm > {
 @public
  ComAqwertianFingeringQwertyMapper *_mapper_;
  IOSIntArray *_frequency_;
  id<JavaUtilList> _firstKeys_;
}

@property (nonatomic, strong) ComAqwertianFingeringQwertyMapper *_mapper;
@property (nonatomic, strong) IOSIntArray *_frequency;
@property (nonatomic, strong) id<JavaUtilList> _firstKeys;

- (id)initWithComAqwertianFingeringQwertyMapper:(ComAqwertianFingeringQwertyMapper *)m
withComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:(ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)level;
+ (IOSIntArray *)FREQUENCY_INTERMEDIATE;
+ (IOSIntArray *)FREQUENCY_BEGINNER;
+ (IOSIntArray *)FREQUENCY_ADVANCED;
+ (IOSIntArray *)FREQUENCY_EXPERT;
+ (int)countWithJavaLangIntegerArray:(IOSIntArray *)values;
- (NSString *)getInfo;
- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)nts
withComAqwertianFingeringPatternList:(ComAqwertianFingeringPatternList *)patterns
                  withJavaUtilMap:(id<JavaUtilMap>)notesHistogram;
- (ComAqwertianFingeringUsageAlgorithm_NextKey *)calcNextKeyWithComAqwertianFingeringQwertyMapper_KeyHistory:(ComAqwertianFingeringQwertyMapper_KeyHistory *)history
                                                                     withComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)currNote
                                                                                    withJavaLangIntegerArray:(IOSIntArray *)freq
                                                                                    withJavaLangIntegerArray:(IOSIntArray *)used;
- (id<JavaUtilList>)getFirstKeys;
- (int)matchPatternWithComAqwertianFingeringMusicFile_NoteArray:(IOSObjectArray *)notes
                           withComAqwertianFingeringPatternList:(ComAqwertianFingeringPatternList *)patterns
                                                        withInt:(int)count;
- (int)matchChordWithComAqwertianFingeringMusicFile_NoteArray:(IOSObjectArray *)notes
                                                      withInt:(int)count;
+ (IOSObjectArray *)_chording;
+ (void)set_chordingWithComAqwertianFingeringUsageAlgorithm_ChordFingerArray:(IOSObjectArray *)_chording;
- (int)processChordWithJavaUtilList:(id<JavaUtilList>)chord;
- (ComAqwertianFingeringUsageAlgorithm_ChordFinger *)findChordFingeringWithInt:(int)note;
@end

@interface ComAqwertianFingeringUsageAlgorithm_NextKey : NSObject {
 @public
  int index_;
  NSString *reason_;
}

@property (nonatomic, assign) int index;
@property (nonatomic, copy) NSString *reason;

@end

@interface ComAqwertianFingeringUsageAlgorithm_ChordFinger : NSObject {
 @public
  int maxMidi_;
  IOSCharArray *fingers_;
}

@property (nonatomic, assign) int maxMidi;
@property (nonatomic, strong) IOSCharArray *fingers;

- (id)initWithInt:(int)max
     withNSString:(NSString *)f;
@end

@interface ComAqwertianFingeringUsageAlgorithm_$1 : NSObject < ComAqwertianFingeringPatternList_NoteFinder > {
 @public
  ComAqwertianFingeringUsageAlgorithm *this$0_;
  int val$count_;
  IOSObjectArray *val$notes_;
}

@property (nonatomic, strong) ComAqwertianFingeringUsageAlgorithm *this$0;
@property (nonatomic, assign) int val$count;
@property (nonatomic, strong) IOSObjectArray *val$notes;

- (int)getNoteWithInt:(int)index;
- (id)initWithComAqwertianFingeringUsageAlgorithm:(ComAqwertianFingeringUsageAlgorithm *)outer$2
                                          withInt:(int)outer$0
                                withNSObjectArray:(IOSObjectArray *)outer$1;
@end

@interface ComAqwertianFingeringUsageAlgorithm_$2 : NSObject < JavaUtilComparator > {
 @public
  ComAqwertianFingeringUsageAlgorithm *this$0_;
}

@property (nonatomic, strong) ComAqwertianFingeringUsageAlgorithm *this$0;

- (int)compareWithId:(ComAqwertianFingeringMusicFile_Note *)n1
              withId:(ComAqwertianFingeringMusicFile_Note *)n2;
- (id)initWithComAqwertianFingeringUsageAlgorithm:(ComAqwertianFingeringUsageAlgorithm *)outer$0;
@end
