//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/GoogleDrive/Aqwertian/MidiFile.java
//
//  Created by nziebart on 9/15/12.
//

@class AqwertianFingeringMidiFile_Chunk;
@class AqwertianFingeringMidiFile_Event;
@class AqwertianFingeringMidiFile_LengthInfo;
@class IOSByteArray;
@class JavaIoInputStream;
@class JavaLangStringBuffer;
@protocol JavaUtilCollection;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "MidiFile.h"
#import "MusicFile.h"
#import "java/lang/Comparable.h"

@interface AqwertianFingeringMidiFile : AqwertianFingeringMusicFile {
 @public
  int _format_;
  int _numTracks_;
  int _division_;
  id<JavaUtilList> _events_;
}

@property (nonatomic, assign) int _format;
@property (nonatomic, assign) int _numTracks;
@property (nonatomic, assign) int _division;
@property (nonatomic, retain) id<JavaUtilList> _events;

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (int)getChannelCount;
- (id<JavaUtilList>)extractNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels;
- (int)getDefaultDuration;
- (BOOL)processChannelWithJavaUtilCollection:(id<JavaUtilCollection>)channels
        withAqwertianFingeringMidiFile_Event:(AqwertianFingeringMidiFile_Event *)e;
- (NSString *)description;
- (void)calcTimeWithJavaUtilList:(id<JavaUtilList>)events
                         withInt:(int)start;
- (AqwertianFingeringMidiFile_Chunk *)readChunkWithJavaIoInputStream:(JavaIoInputStream *)inArg;
+ (AqwertianFingeringMidiFile_LengthInfo *)readVarLengthWithJavaLangByteArray:(IOSByteArray *)data
                                                                      withInt:(int)offset;
@end

@interface AqwertianFingeringMidiFile_Chunk : NSObject {
 @public
  NSString *id__;
  int length_;
}

@property (nonatomic, copy) NSString *id_;
@property (nonatomic, assign) int length;

- (id)initWithNSString:(NSString *)id_
               withInt:(int)length;
@end

@interface AqwertianFingeringMidiFile_GenericChunk : AqwertianFingeringMidiFile_Chunk {
}

- (id)initWithNSString:(NSString *)id_
               withInt:(int)length;
@end

@interface AqwertianFingeringMidiFile_MThdChunk : AqwertianFingeringMidiFile_Chunk {
 @public
  int format_;
  int numTracks_;
  int division_;
}

@property (nonatomic, assign) int format;
@property (nonatomic, assign) int numTracks;
@property (nonatomic, assign) int division;

- (id)initWithNSString:(NSString *)id_
               withInt:(int)length
 withJavaLangByteArray:(IOSByteArray *)data;
@end

@interface AqwertianFingeringMidiFile_MTrkChunk : AqwertianFingeringMidiFile_Chunk {
 @public
  id<JavaUtilList> events_;
}

@property (nonatomic, retain) id<JavaUtilList> events;

- (id)initWithNSString:(NSString *)id_
               withInt:(int)length
 withJavaLangByteArray:(IOSByteArray *)data;
- (void)parseChunkWithInt:(int)len
    withJavaLangByteArray:(IOSByteArray *)data;
- (int)dataLengthWithChar:(char)status;
- (int)parseMetaEventWithAqwertianFingeringMidiFile_Event:(AqwertianFingeringMidiFile_Event *)e
                                    withJavaLangByteArray:(IOSByteArray *)data
                                                  withInt:(int)offset;
@end

@interface AqwertianFingeringMidiFile_Event : NSObject < JavaLangComparable > {
 @public
  int deltaTime_;
  int time_;
  char status_;
  IOSByteArray *data_;
  BOOL visited_;
}

@property (nonatomic, assign) int deltaTime;
@property (nonatomic, assign) int time;
@property (nonatomic, assign) char status;
@property (nonatomic, retain) IOSByteArray *data;
@property (nonatomic, assign) BOOL visited;

- (BOOL)isChannelEvent;
- (BOOL)isNoteEvent;
- (BOOL)isNoteOn;
- (BOOL)isNoteOff;
- (int)getChannel;
- (int)getNote;
- (BOOL)isEqual:(id)obj;
- (int)compareToWithId:(AqwertianFingeringMidiFile_Event *)e;
- (NSString *)description;
- (void)toStringWithJavaLangStringBuffer:(JavaLangStringBuffer *)buff;
@end

@interface AqwertianFingeringMidiFile_LengthInfo : NSObject {
 @public
  int length_;
  int offset_;
}

@property (nonatomic, assign) int length;
@property (nonatomic, assign) int offset;

- (id)initWithInt:(int)length
          withInt:(int)offset;
@end
