//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/GoogleDrive/Aqwertian/MusNotesFile.java
//
//  Created by nziebart on 9/15/12.
//

@class AqwertianFingeringMusNotesFile_MusElement_TypeEnum;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol JavaUtilCollection;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "MusNotesFile.h"
#import "MusicFile.h"
#import "java/lang/Enum.h"

@interface AqwertianFingeringMusNotesFile : AqwertianFingeringMusicFile {
 @public
  id<JavaUtilList> _elements_;
}

@property (nonatomic, retain) id<JavaUtilList> _elements;

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (int)getChannelCount;
- (id<JavaUtilList>)extractNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels;
- (void)storeWithJavaIoOutputStream:(JavaIoOutputStream *)o;
- (NSString *)description;
@end

typedef enum {
  AqwertianFingeringMusNotesFile_MusElement_Type_PIECE = 0,
  AqwertianFingeringMusNotesFile_MusElement_Type_MEASURE = 1,
  AqwertianFingeringMusNotesFile_MusElement_Type_NOTE = 2,
  AqwertianFingeringMusNotesFile_MusElement_Type_MARK = 3,
} AqwertianFingeringMusNotesFile_MusElement_Type;

@interface AqwertianFingeringMusNotesFile_MusElement_TypeEnum : JavaLangEnum < NSCopying > {
 @public
  NSString *prefix_;
}
@property (nonatomic, copy) NSString *prefix;

+ (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)PIECE;
+ (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)MEASURE;
+ (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)NOTE;
+ (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)MARK;
+ (IOSObjectArray *)values;
+ (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)prefix
          withNSString:(NSString *)name
               withInt:(int)ordinal;
- (NSString *)getPrefix;
+ (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)fromPrefixWithNSString:(NSString *)prefix;
@end

@protocol AqwertianFingeringMusNotesFile_MusElement < NSObject >
- (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)getType;
- (NSString *)getLine;
@end

@interface AqwertianFingeringMusNotesFile_BasicElement : NSObject < AqwertianFingeringMusNotesFile_MusElement > {
 @public
  AqwertianFingeringMusNotesFile_MusElement_TypeEnum *_type_;
  id<JavaUtilList> _words_;
}

@property (nonatomic, retain) AqwertianFingeringMusNotesFile_MusElement_TypeEnum *_type;
@property (nonatomic, retain) id<JavaUtilList> _words;

+ (id<AqwertianFingeringMusNotesFile_MusElement>)createWithNSString:(NSString *)line;
- (id)initWithNSString:(NSString *)line;
+ (id<JavaUtilList>)parseLineWithNSString:(NSString *)line;
+ (NSString *)composeLineWithJavaUtilList:(id<JavaUtilList>)words;
- (NSString *)getLine;
- (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)getType;
@end

@interface AqwertianFingeringMusNotesFile_MusPiece : AqwertianFingeringMusNotesFile_BasicElement {
}

- (id)initWithNSString:(NSString *)line;
@end

@interface AqwertianFingeringMusNotesFile_MusNote : AqwertianFingeringMusicFile_Note < AqwertianFingeringMusNotesFile_MusElement > {
 @public
  id<JavaUtilList> _words_;
}

@property (nonatomic, retain) id<JavaUtilList> _words;

- (id)initWithNSString:(NSString *)line;
- (NSString *)getLine;
- (AqwertianFingeringMusNotesFile_MusElement_TypeEnum *)getType;
- (BOOL)isTieNote;
- (void)adjustWords;
@end
