//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/GoogleDrive/Aqwertian/Aqwertian/fingering/MapAlgorithm.java
//
//  Created by nziebart on 9/17/12.
//

void AqwertianFingeringMapAlgorithm_unused() {}
