//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/GoogleDrive/Aqwertian/Aqwertian/fingering/MusicFile.java
//
//  Created by nziebart on 9/17/12.
//

@class AqwertianFingeringMusicFile_Note;
@class IOSByteArray;
@class IOSObjectArray;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@protocol JavaUtilCollection;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "java/lang/Comparable.h"

@interface AqwertianFingeringMusicFile : NSObject {
 @public
  id<JavaUtilMap> _notes_;
}

@property (nonatomic, strong) id<JavaUtilMap> _notes;

- (id)init;
- (int)getChannelCount;
- (id<JavaUtilList>)getNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels;
- (void)sortNotesWithJavaUtilList:(id<JavaUtilList>)notes;
- (BOOL)sameNoteWithAqwertianFingeringMusicFile_Note:(AqwertianFingeringMusicFile_Note *)n1
                withAqwertianFingeringMusicFile_Note:(AqwertianFingeringMusicFile_Note *)n2;
- (void)storeWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;
- (id<JavaUtilList>)extractNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels;
- (int)readWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (void)readWithJavaIoInputStream:(JavaIoInputStream *)inArg
            withJavaLangByteArray:(IOSByteArray *)buff
                          withInt:(int)length;
@end

@interface AqwertianFingeringMusicFile_Note : NSObject < JavaLangComparable > {
 @public
  int channel_;
  int time_;
  int duration_;
  int note_;
  unichar qwerty_;
  NSString *reason_;
}

@property (nonatomic, assign) int channel;
@property (nonatomic, assign) int time;
@property (nonatomic, assign) int duration;
@property (nonatomic, assign) int note;
@property (nonatomic, assign) unichar qwerty;
@property (nonatomic, copy) NSString *reason;

- (id)initWithInt:(int)channel
          withInt:(int)time
          withInt:(int)duration
          withInt:(int)note;
+ (IOSObjectArray *)NOTES;
- (NSString *)getNoteName;
+ (NSString *)getNoteNameWithInt:(int)note;
- (int)getOctave;
+ (int)getOctaveWithInt:(int)note;
- (NSString *)getNoteValue;
+ (NSString *)getNoteValueWithInt:(int)note;
- (int)compareToWithId:(AqwertianFingeringMusicFile_Note *)n;
- (NSString *)description;
@end
