//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/GoogleDrive/Aqwertian/Aqwertian/fingering/QwertyMapper.java
//
//  Created by nziebart on 9/17/12.
//

@class AqwertianFingeringMusicFile_Note;
@class AqwertianFingeringPatternList;
@class AqwertianFingeringQwertyMapper_AlgorithmEnum;
@class AqwertianFingeringQwertyMapper_KeyHistory;
@class AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum;
@class IOSObjectArray;
@class JavaUtilLinkedList;
@class JavaUtilRandom;
@protocol AqwertianFingeringMapAlgorithm;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "java/lang/Enum.h"

#define AqwertianFingeringQwertyMapper_FINGER_START ' '
#define AqwertianFingeringQwertyMapper_USAGE_LIMIT 5

@interface AqwertianFingeringQwertyMapper : NSObject {
 @public
  id<AqwertianFingeringMapAlgorithm> _algo_;
  id<JavaUtilMap> _noteHist_;
  JavaUtilRandom *rand_;
}

@property (nonatomic, strong) id<AqwertianFingeringMapAlgorithm> _algo;
@property (nonatomic, strong) id<JavaUtilMap> _noteHist;
@property (nonatomic, strong) JavaUtilRandom *rand;

+ (IOSObjectArray *)FINGER;
+ (unichar)FINGER_START;
- (id)initWithAqwertianFingeringQwertyMapper_AlgorithmEnum:(AqwertianFingeringQwertyMapper_AlgorithmEnum *)algorithm
  withAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:(AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)level
                                        withJavaUtilRandom:(JavaUtilRandom *)rand;
- (id)initWithAqwertianFingeringQwertyMapper_AlgorithmEnum:(AqwertianFingeringQwertyMapper_AlgorithmEnum *)algorithm
  withAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:(AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)level;
- (NSString *)getInfo;
- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)notes
withAqwertianFingeringPatternList:(AqwertianFingeringPatternList *)patterns;
+ (unichar)getHandWithInt:(int)qwerty;
+ (NSString *)getFingerWithInt:(int)qwerty;
+ (int)getRowWithInt:(int)qwerty;
+ (unichar)getQwertyWithNSString:(NSString *)finger
                         withInt:(int)row;
+ (unichar)getKeyWithInt:(int)index;
+ (int)getIndexWithUnichar:(unichar)key;
- (AqwertianFingeringQwertyMapper_KeyHistory *)createKeyHistory;
- (BOOL)ruleFailsWithAqwertianFingeringQwertyMapper_KeyHistory:(AqwertianFingeringQwertyMapper_KeyHistory *)history
                          withAqwertianFingeringMusicFile_Note:(AqwertianFingeringMusicFile_Note *)currNote
                                                   withUnichar:(unichar)key;
- (BOOL)isImpossibleFingerWithNSString:(NSString *)prevFinger
                          withNSString:(NSString *)nextFinger;
- (NSString *)toStringWithAqwertianFingeringMusicFile_Note:(AqwertianFingeringMusicFile_Note *)n;
- (void)addToHistogramWithJavaUtilMap:(id<JavaUtilMap>)hist
                         withNSString:(NSString *)key;
- (void)printStatisticsWithJavaUtilCollection:(id<JavaUtilCollection>)notes;
- (void)printHistogramWithJavaUtilMap:(id<JavaUtilMap>)hist
                         withNSString:(NSString *)title;
@end

typedef enum {
  AqwertianFingeringQwertyMapper_Algorithm_RANDOM = 0,
  AqwertianFingeringQwertyMapper_Algorithm_ROUND_ROBIN = 1,
  AqwertianFingeringQwertyMapper_Algorithm_USAGE = 2,
} AqwertianFingeringQwertyMapper_Algorithm;

@interface AqwertianFingeringQwertyMapper_AlgorithmEnum : JavaLangEnum < NSCopying > {
}
+ (AqwertianFingeringQwertyMapper_AlgorithmEnum *)RANDOM;
+ (AqwertianFingeringQwertyMapper_AlgorithmEnum *)ROUND_ROBIN;
+ (AqwertianFingeringQwertyMapper_AlgorithmEnum *)USAGE;
+ (IOSObjectArray *)values;
+ (AqwertianFingeringQwertyMapper_AlgorithmEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

typedef enum {
  AqwertianFingeringQwertyMapper_LevelOfDifficulty_BEGINNER = 0,
  AqwertianFingeringQwertyMapper_LevelOfDifficulty_INTERMEDIATE = 1,
  AqwertianFingeringQwertyMapper_LevelOfDifficulty_ADVANCED = 2,
  AqwertianFingeringQwertyMapper_LevelOfDifficulty_EXPERT = 3,
} AqwertianFingeringQwertyMapper_LevelOfDifficulty;

@interface AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum : JavaLangEnum < NSCopying > {
}
+ (AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)BEGINNER;
+ (AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)INTERMEDIATE;
+ (AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)ADVANCED;
+ (AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)EXPERT;
+ (IOSObjectArray *)values;
+ (AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface AqwertianFingeringQwertyMapper_KeyHistory : NSObject {
 @public
  JavaUtilLinkedList *_mapped_;
  JavaUtilLinkedList *_playing_;
}

@property (nonatomic, strong) JavaUtilLinkedList *_mapped;
@property (nonatomic, strong) JavaUtilLinkedList *_playing;

- (id)init;
- (void)addNoteWithAqwertianFingeringMusicFile_Note:(AqwertianFingeringMusicFile_Note *)n;
- (AqwertianFingeringMusicFile_Note *)getPrevious;
- (AqwertianFingeringMusicFile_Note *)findMappedNoteWithAqwertianFingeringMusicFile_Note:(AqwertianFingeringMusicFile_Note *)n;
- (BOOL)isPlayingWithAqwertianFingeringMusicFile_Note:(AqwertianFingeringMusicFile_Note *)note;
- (BOOL)isFingerDownWithNSString:(NSString *)nextFinger;
@end
