//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/GoogleDrive/Aqwertian/Aqwertian/fingering/RandomAlgorithm.java
//
//  Created by nziebart on 9/17/12.
//

@class AqwertianFingeringPatternList;
@class AqwertianFingeringQwertyMapper;
@class JavaUtilRandom;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "Aqwertian/fingering/MapAlgorithm.h"

@interface AqwertianFingeringRandomAlgorithm : NSObject < AqwertianFingeringMapAlgorithm > {
 @public
  JavaUtilRandom *rand_;
}

@property (nonatomic, strong) JavaUtilRandom *rand;

- (id)initWithAqwertianFingeringQwertyMapper:(AqwertianFingeringQwertyMapper *)m;
- (NSString *)getInfo;
- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)notes
withAqwertianFingeringPatternList:(AqwertianFingeringPatternList *)patterns
                  withJavaUtilMap:(id<JavaUtilMap>)notesHistogram;
@end
