//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/GoogleDrive/Aqwertian/Aqwertian/fingering/UsageAlgorithm.java
//
//  Created by nziebart on 9/17/12.
//

@class AqwertianFingeringMusicFile_Note;
@class AqwertianFingeringPatternList;
@class AqwertianFingeringQwertyMapper;
@class AqwertianFingeringQwertyMapper_KeyHistory;
@class AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum;
@class AqwertianFingeringUsageAlgorithm_ChordFinger;
@class AqwertianFingeringUsageAlgorithm_NextKey;
@class IOSCharArray;
@class IOSIntArray;
@class IOSObjectArray;
@protocol JavaUtilCollection;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "Aqwertian/fingering/MapAlgorithm.h"
#import "Aqwertian/fingering/PatternList.h"
#import "java/util/Comparator.h"

@interface AqwertianFingeringUsageAlgorithm : NSObject < AqwertianFingeringMapAlgorithm > {
 @public
  AqwertianFingeringQwertyMapper *_mapper_;
  IOSIntArray *_frequency_;
  id<JavaUtilList> _firstKeys_;
}

@property (nonatomic, strong) AqwertianFingeringQwertyMapper *_mapper;
@property (nonatomic, strong) IOSIntArray *_frequency;
@property (nonatomic, strong) id<JavaUtilList> _firstKeys;

- (id)initWithAqwertianFingeringQwertyMapper:(AqwertianFingeringQwertyMapper *)m
withAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:(AqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)level;
+ (IOSIntArray *)FREQUENCY_INTERMEDIATE;
+ (IOSIntArray *)FREQUENCY_BEGINNER;
+ (IOSIntArray *)FREQUENCY_ADVANCED;
+ (IOSIntArray *)FREQUENCY_EXPERT;
+ (int)countWithJavaLangIntegerArray:(IOSIntArray *)values;
- (NSString *)getInfo;
- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)nts
withAqwertianFingeringPatternList:(AqwertianFingeringPatternList *)patterns
                  withJavaUtilMap:(id<JavaUtilMap>)notesHistogram;
- (AqwertianFingeringUsageAlgorithm_NextKey *)calcNextKeyWithAqwertianFingeringQwertyMapper_KeyHistory:(AqwertianFingeringQwertyMapper_KeyHistory *)history
                                                                  withAqwertianFingeringMusicFile_Note:(AqwertianFingeringMusicFile_Note *)currNote
                                                                              withJavaLangIntegerArray:(IOSIntArray *)freq
                                                                              withJavaLangIntegerArray:(IOSIntArray *)used;
- (id<JavaUtilList>)getFirstKeys;
- (int)matchPatternWithAqwertianFingeringMusicFile_NoteArray:(IOSObjectArray *)notes
                           withAqwertianFingeringPatternList:(AqwertianFingeringPatternList *)patterns
                                                     withInt:(int)count;
- (int)matchChordWithAqwertianFingeringMusicFile_NoteArray:(IOSObjectArray *)notes
                                                   withInt:(int)count;
+ (IOSObjectArray *)_chording;
+ (void)set_chordingWithAqwertianFingeringUsageAlgorithm_ChordFingerArray:(IOSObjectArray *)_chording;
- (int)processChordWithJavaUtilList:(id<JavaUtilList>)chord;
- (AqwertianFingeringUsageAlgorithm_ChordFinger *)findChordFingeringWithInt:(int)note;
@end

@interface AqwertianFingeringUsageAlgorithm_NextKey : NSObject {
 @public
  int index_;
  NSString *reason_;
}

@property (nonatomic, assign) int index;
@property (nonatomic, copy) NSString *reason;

@end

@interface AqwertianFingeringUsageAlgorithm_ChordFinger : NSObject {
 @public
  int maxMidi_;
  IOSCharArray *fingers_;
}

@property (nonatomic, assign) int maxMidi;
@property (nonatomic, strong) IOSCharArray *fingers;

- (id)initWithInt:(int)max
     withNSString:(NSString *)f;
@end

@interface AqwertianFingeringUsageAlgorithm_$1 : NSObject < AqwertianFingeringPatternList_NoteFinder > {
 @public
  AqwertianFingeringUsageAlgorithm *this$0_;
  int val$count_;
  IOSObjectArray *val$notes_;
}

@property (nonatomic, strong) AqwertianFingeringUsageAlgorithm *this$0;
@property (nonatomic, assign) int val$count;
@property (nonatomic, strong) IOSObjectArray *val$notes;

- (int)getNoteWithInt:(int)index;
- (id)initWithAqwertianFingeringUsageAlgorithm:(AqwertianFingeringUsageAlgorithm *)outer$2
                                       withInt:(int)outer$0
                             withNSObjectArray:(IOSObjectArray *)outer$1;
@end

@interface AqwertianFingeringUsageAlgorithm_$2 : NSObject < JavaUtilComparator > {
 @public
  AqwertianFingeringUsageAlgorithm *this$0_;
}

@property (nonatomic, strong) AqwertianFingeringUsageAlgorithm *this$0;

- (int)compareWithId:(AqwertianFingeringMusicFile_Note *)n1
              withId:(AqwertianFingeringMusicFile_Note *)n2;
- (id)initWithAqwertianFingeringUsageAlgorithm:(AqwertianFingeringUsageAlgorithm *)outer$0;
@end
