//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/GoogleDrive/Aqwertian/Aqwertian/fingering/MapAlgorithm.java
//
//  Created by nziebart on 9/17/12.
//

@class AqwertianFingeringPatternList;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@protocol AqwertianFingeringMapAlgorithm < NSObject >
- (NSString *)getInfo;
- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)notes
withAqwertianFingeringPatternList:(AqwertianFingeringPatternList *)patterns
                  withJavaUtilMap:(id<JavaUtilMap>)notesHistogram;
@end
