//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/MidiFile.java
//
//  Created by nziebart on 1/27/13.
//

@class ComAqwertianFingeringMidiFile_Chunk;
@class ComAqwertianFingeringMidiFile_Event;
@class ComAqwertianFingeringMidiFile_LengthInfo;
@class IOSByteArray;
@class JavaIoInputStream;
@class JavaLangStringBuffer;
@protocol JavaUtilCollection;
@protocol JavaUtilList;

#import "JreEmulation.h"
#import "MidiFile.h"
#import "MusicFile.h"
#import "java/lang/Comparable.h"

@interface ComAqwertianFingeringMidiFile : ComAqwertianFingeringMusicFile {
 @public
  int _format_;
  int _numTracks_;
  int _ticksPerBeat_;
  id<JavaUtilList> _events_;
}

@property (nonatomic, assign) int _format;
@property (nonatomic, assign) int _numTracks;
@property (nonatomic, assign) int _ticksPerBeat;
@property (nonatomic, strong) id<JavaUtilList> _events;

+ (int)toIntWithChar:(char)a
            withChar:(char)b;
- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (int)getChannelCount;
- (id<JavaUtilList>)extractNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels;
- (BOOL)processChannelWithJavaUtilCollection:(id<JavaUtilCollection>)channels
     withComAqwertianFingeringMidiFile_Event:(ComAqwertianFingeringMidiFile_Event *)e;
- (NSString *)description;
- (void)calcTimeWithJavaUtilList:(id<JavaUtilList>)events
                         withInt:(int)start;
- (ComAqwertianFingeringMidiFile_Chunk *)readChunkWithJavaIoInputStream:(JavaIoInputStream *)inArg;
+ (ComAqwertianFingeringMidiFile_LengthInfo *)readVarLengthWithJavaLangByteArray:(IOSByteArray *)data
                                                                         withInt:(int)offset;
@end

@interface ComAqwertianFingeringMidiFile_Chunk : NSObject {
 @public
  NSString *id__;
  int length_;
}

@property (nonatomic, copy) NSString *id_;
@property (nonatomic, assign) int length;

- (id)initWithNSString:(NSString *)id_
               withInt:(int)length;
@end

@interface ComAqwertianFingeringMidiFile_GenericChunk : ComAqwertianFingeringMidiFile_Chunk {
}

- (id)initWithNSString:(NSString *)id_
               withInt:(int)length;
@end

@interface ComAqwertianFingeringMidiFile_MThdChunk : ComAqwertianFingeringMidiFile_Chunk {
 @public
  int format_;
  int numTracks_;
  int ticksPerBeat_;
}

@property (nonatomic, assign) int format;
@property (nonatomic, assign) int numTracks;
@property (nonatomic, assign) int ticksPerBeat;

- (id)initWithNSString:(NSString *)id_
               withInt:(int)length
 withJavaLangByteArray:(IOSByteArray *)data;
@end

@interface ComAqwertianFingeringMidiFile_MTrkChunk : ComAqwertianFingeringMidiFile_Chunk {
 @public
  id<JavaUtilList> events_;
}

@property (nonatomic, strong) id<JavaUtilList> events;

- (id)initWithNSString:(NSString *)id_
               withInt:(int)length
 withJavaLangByteArray:(IOSByteArray *)data;
- (void)parseChunkWithInt:(int)len
    withJavaLangByteArray:(IOSByteArray *)data;
- (int)dataLengthWithChar:(char)status;
- (int)parseMetaEventWithComAqwertianFingeringMidiFile_Event:(ComAqwertianFingeringMidiFile_Event *)e
                                       withJavaLangByteArray:(IOSByteArray *)data
                                                     withInt:(int)offset;
@end

@interface ComAqwertianFingeringMidiFile_Event : NSObject < JavaLangComparable > {
 @public
  int deltaTime_;
  int time_;
  char status_;
  IOSByteArray *data_;
  BOOL visited_;
}

@property (nonatomic, assign) int deltaTime;
@property (nonatomic, assign) int time;
@property (nonatomic, assign) char status;
@property (nonatomic, strong) IOSByteArray *data;
@property (nonatomic, assign) BOOL visited;

- (BOOL)isChannelEvent;
- (BOOL)isNoteEvent;
- (BOOL)isNoteOn;
- (BOOL)isNoteOff;
- (BOOL)isLyrics;
- (BOOL)isTempoChange;
- (int)getChannel;
- (int)getNote;
- (int)getVelocity;
- (int)getTempo;
- (NSString *)getLyrics;
- (BOOL)isEqual:(id)obj;
- (int)compareToWithId:(ComAqwertianFingeringMidiFile_Event *)e;
- (NSString *)description;
- (void)toStringWithJavaLangStringBuffer:(JavaLangStringBuffer *)buff;
@end

@interface ComAqwertianFingeringMidiFile_LengthInfo : NSObject {
 @public
  int length_;
  int offset_;
}

@property (nonatomic, assign) int length;
@property (nonatomic, assign) int offset;

- (id)initWithInt:(int)length
          withInt:(int)offset;
@end
