//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/MusicFile.java
//
//  Created by nziebart on 1/27/13.
//

#import "IOSByteArray.h"
#import "IOSObjectArray.h"
#import "MusicFile.h"
#import "java/io/IOException.h"
#import "java/io/InputStream.h"
#import "java/lang/Integer.h"
#import "java/util/Collection.h"
#import "java/util/Collections.h"
#import "java/util/HashMap.h"
#import "java/util/Iterator.h"
#import "java/util/List.h"
#import "java/util/Map.h"

@implementation ComAqwertianFingeringMusicFile

- (id<JavaUtilMap>)_notes {
  return _notes_;
}

- (void)set_notes:(id<JavaUtilMap>)new_notes {
  _notes_ = new_notes;
}


- (id)init {
  if ((self = [super init])) {
    _notes_ = [[JavaUtilHashMap alloc] init];
  }
  return self;
}

- (int)getChannelCount {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<JavaUtilList>)getNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels {
  if (((id<JavaUtilList>) [((id<JavaUtilMap>) NIL_CHK(_notes_)) getWithId:channels]) == nil) {
    id<JavaUtilList> notes = [self extractNotesWithJavaUtilCollection:channels];
    [self sortNotesWithJavaUtilList:notes];
    [((id<JavaUtilMap>) NIL_CHK(_notes_)) putWithId:channels withId:notes];
  }
  return (id<JavaUtilList>) ((id<JavaUtilList>) [((id<JavaUtilMap>) NIL_CHK(_notes_)) getWithId:channels]);
}

- (void)sortNotesWithJavaUtilList:(id<JavaUtilList>)notes {
  [JavaUtilCollections sortWithJavaUtilList:notes];
  ComAqwertianFingeringMusicFile_Note *prev = nil;
  for (id<JavaUtilIterator> it = ((id<JavaUtilIterator>) [((id<JavaUtilList>) NIL_CHK(notes)) iterator]); [((id<JavaUtilIterator>) NIL_CHK(it)) hasNext]; ) {
    ComAqwertianFingeringMusicFile_Note *n = ((ComAqwertianFingeringMusicFile_Note *) [((id<JavaUtilIterator>) NIL_CHK(it)) next]);
    if ([self sameNoteWithComAqwertianFingeringMusicFile_Note:prev withComAqwertianFingeringMusicFile_Note:n]) {
      [((id<JavaUtilIterator>) NIL_CHK(it)) remove];
    }
    prev = n;
  }
}

- (BOOL)sameNoteWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n1
                withComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n2 {
  if (n1 == nil && n2 != nil || n1 != nil && n2 == nil) {
    return NO;
  }
  if (n1 == nil && n2 == nil) {
    return YES;
  }
  return ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n1)).note == ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n2)).note && ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n1)).duration == ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n2)).duration && ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n1)).time == ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n2)).time;
}

- (id<JavaUtilList>)extractNotesWithJavaUtilCollection:(id<JavaUtilCollection>)channels {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (int)readWithJavaIoInputStream:(JavaIoInputStream *)inArg {
  int val = [((JavaIoInputStream *) NIL_CHK(inArg)) read];
  if (val < 0) @throw [[JavaIoIOException alloc] initWithNSString:@"Premature end of file."];
  return val;
}

- (void)readWithJavaIoInputStream:(JavaIoInputStream *)inArg
            withJavaLangByteArray:(IOSByteArray *)buff
                          withInt:(int)length {
  int val = [((JavaIoInputStream *) NIL_CHK(inArg)) readWithJavaLangByteArray:buff withInt:0 withInt:length];
  if (val != length) @throw [[JavaIoIOException alloc] initWithNSString:[NSString stringWithFormat:@"Premature end of file. Expected: %d; read: %d", length, val]];
}

@end


@implementation ComAqwertianFingeringMusicFile_Note

static IOSObjectArray * ComAqwertianFingeringMusicFile_Note_NOTES_;

- (int)channel {
  return channel_;
}

- (void)setChannel:(int)newChannel {
  channel_ = newChannel;
}

- (int)time {
  return time_;
}

- (void)setTime:(int)newTime {
  time_ = newTime;
}

- (int)duration {
  return duration_;
}

- (void)setDuration:(int)newDuration {
  duration_ = newDuration;
}

- (int)note {
  return note_;
}

- (void)setNote:(int)newNote {
  note_ = newNote;
}

- (int)volume {
  return volume_;
}

- (void)setVolume:(int)newVolume {
  volume_ = newVolume;
}

- (int)rate {
  return rate_;
}

- (void)setRate:(int)newRate {
  rate_ = newRate;
}

- (NSString *)lyrics {
  return lyrics_;
}

- (void)setLyrics:(NSString *)newLyrics {
  lyrics_ = newLyrics;
}

- (unichar)qwerty {
  return qwerty_;
}

- (void)setQwerty:(unichar)newQwerty {
  qwerty_ = newQwerty;
}

- (NSString *)reason {
  return reason_;
}

- (void)setReason:(NSString *)newReason {
  reason_ = newReason;
}

- (id)init {
    if ((self = [super init])) {
    _tie = NO;
    _removedFromUserNotes = NO;
        _overlays = [NSMutableArray new];
    }
    return self;
}

- (id)initWithInt:(int)channel
          withInt:(int)time
          withInt:(int)duration
          withInt:(int)note
          withInt:(int)volume
          withInt:(int)rate
     withNSString:(NSString *)lyrics {
  if ((self = [super init])) {
    self.channel = channel;
    self.time = time;
    self.duration = duration;
    self.note = note;
    self.volume = volume;
    self.rate = rate;
    self.lyrics = lyrics;
      _tie = NO;
      self.overlays = @[].mutableCopy;
  }
  return self;
}

+ (IOSObjectArray *)NOTES {
  return ComAqwertianFingeringMusicFile_Note_NOTES_;
}

- (NSString *)getNoteName {
  return [ComAqwertianFingeringMusicFile_Note getNoteNameWithInt:note_];
}

+ (NSString *)getNoteNameWithInt:(int)note {
  return [((IOSObjectArray *) NIL_CHK(ComAqwertianFingeringMusicFile_Note_NOTES_)) objectAtIndex:note % 12];
}

- (int)getOctave {
  return [ComAqwertianFingeringMusicFile_Note getOctaveWithInt:note_];
}

+ (int)getOctaveWithInt:(int)note {
  return note / 12;
}

- (NSString *)getNoteValue {
  return [ComAqwertianFingeringMusicFile_Note getNoteValueWithInt:note_];
}

+ (NSString *)getNoteValueWithInt:(int)note {
  return [NSString stringWithFormat:@"%d%@", [ComAqwertianFingeringMusicFile_Note getOctaveWithInt:note], [ComAqwertianFingeringMusicFile_Note getNoteNameWithInt:note]];
}

- (BOOL)overlapsWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n {
  return ((time_ >= ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).time) && (time_ < ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).time + ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).duration)) || ((((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).time >= time_) && (((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).time < time_ + duration_));
}

- (int)compareToWithId:(ComAqwertianFingeringMusicFile_Note *)n {
  int ret = time_ - ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).time;
  if (ret != 0) return ret;
  ret = duration_ - ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).duration;
  if (ret != 0) return ret;
  return note_ - ((ComAqwertianFingeringMusicFile_Note *) NIL_CHK(n)).note;
}

- (BOOL)isEqual:(RGNote *)n {
//    if (duration_ && n.duration) {
//        return n.time == time_ && n.note == note_ && n.channel == channel_ && duration_ == n.duration;
//    }
//    if (n.time == time_) {
//        if (n.note == note_) {
//            return YES;
//        }
//    }
//    return n.time == time_ && n.note == note_;
    return n == self;
}

- (NSComparisonResult)compare:(RGNote *)n {
    if (n.time > time_) {
        return NSOrderedAscending;
    } else if (n.time < time_) {
        return NSOrderedDescending;
    } else {
        if (n.duration > duration_) {
            return NSOrderedAscending;
        } else if (n.duration < duration_) {
            return NSOrderedDescending;
        } else {
            if (n.note > note_) {
                return NSOrderedAscending;
            } else if (n.note < note_) {
                return NSOrderedDescending;
            } else {
                if (n.channel > channel_) {
                    return NSOrderedAscending;
                } else if (n.channel < channel_) {
                    return NSOrderedDescending;
                } else {
                    return NSOrderedSame;
                }
            }
        }
    }
}

- (NSString *)description {
    return [NSString stringWithFormat:@"time:%d dur:%d ch:%d note:%d vel:%d q:%c lyric:%@", time_, duration_, channel_, note_, volume_, qwerty_, lyrics_];
}

+ (void)initialize {
  if (self == [ComAqwertianFingeringMusicFile_Note class]) {
    ComAqwertianFingeringMusicFile_Note_NOTES_ = [IOSObjectArray arrayWithObjects:(id[]){ @"C ", @"C#", @"D ", @"D#", @"E ", @"F ", @"F#", @"G ", @"G#", @"A ", @"A#", @"B " } count:12 type:[IOSClass classWithClass:[NSString class]]];
  }
}

@end


