//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nziebart/Documents/MusFingering/com/aqwertian/fingering/QwertyMapper.java
//
//  Created by nziebart on 1/20/13.
//



@class ComAqwertianFingeringMusicFile_Note;
@class ComAqwertianFingeringPatternList;
@class ComAqwertianFingeringQwertyMapper_AlgorithmEnum;
@class ComAqwertianFingeringQwertyMapper_KeyHistory;
@class ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum;
@class IOSObjectArray;
@class JavaUtilLinkedList;
@class JavaUtilRandom;
@protocol ComAqwertianFingeringMapAlgorithm;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "java/lang/Enum.h"

#define ComAqwertianFingeringQwertyMapper_FINGER_START ' '
#define ComAqwertianFingeringQwertyMapper_USAGE_LIMIT 5

int ComAqwertianFingeringQwertyMapper_ChordQuantum();
int ComAqwertianFingeringQwertyMapper_TrillQuantum();

void ComAqwertianFingeringQwertyMapper_SetChordQuantum(int);
void ComAqwertianFingeringQwertyMapper_SetTrillQuantum(int);

@interface ComAqwertianFingeringQwertyMapper : NSObject {
 @public
  id<ComAqwertianFingeringMapAlgorithm> _algo_;
  id<JavaUtilMap> _noteHist_;
  JavaUtilRandom *rand_;
}

@property (nonatomic, strong) id<ComAqwertianFingeringMapAlgorithm> _algo;
@property (nonatomic, strong) id<JavaUtilMap> _noteHist;
@property (nonatomic, strong) JavaUtilRandom *rand;

+ (IOSObjectArray *)FINGER;
+ (unichar)FINGER_START;
- (id)initWithComAqwertianFingeringQwertyMapper_AlgorithmEnum:(ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)algorithm
  withComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:(ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)level
                                           withJavaUtilRandom:(JavaUtilRandom *)rand;
- (id)initWithComAqwertianFingeringQwertyMapper_AlgorithmEnum:(ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)algorithm
  withComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum:(ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)level;
- (NSString *)getInfo;
- (void)mapWithJavaUtilCollection:(id<JavaUtilCollection>)notes
withComAqwertianFingeringPatternList:(ComAqwertianFingeringPatternList *)patterns;
- (void)mapWithNotes:(NSArray *)notes
withComAqwertianFingeringPatternList:(ComAqwertianFingeringPatternList *)patterns;
+ (unichar)getHandWithInt:(int)qwerty;
+ (NSString *)getFingerWithInt:(int)qwerty;
+ (int)getRowWithInt:(int)qwerty;
+ (unichar)getQwertyWithNSString:(NSString *)finger
                         withInt:(int)row;
+ (unichar)getKeyWithInt:(int)index;
+ (int)getIndexWithUnichar:(unichar)key;
- (ComAqwertianFingeringQwertyMapper_KeyHistory *)createKeyHistory;
- (BOOL)ruleFailsWithComAqwertianFingeringQwertyMapper_KeyHistory:(ComAqwertianFingeringQwertyMapper_KeyHistory *)history
                          withComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)currNote
                                                      withUnichar:(unichar)key;
- (BOOL)isImpossibleFingerWithNSString:(NSString *)prevFinger
                          withNSString:(NSString *)nextFinger;
- (NSString *)toStringWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n;
- (void)addToHistogramWithJavaUtilMap:(id<JavaUtilMap>)hist
                         withNSString:(NSString *)key;
- (void)printStatisticsWithJavaUtilCollection:(id<JavaUtilCollection>)notes;
- (void)printHistogramWithJavaUtilMap:(id<JavaUtilMap>)hist
                         withNSString:(NSString *)title;
@end

typedef enum {
  ComAqwertianFingeringQwertyMapper_Algorithm_RANDOM = 0,
  ComAqwertianFingeringQwertyMapper_Algorithm_ROUND_ROBIN = 1,
  ComAqwertianFingeringQwertyMapper_Algorithm_USAGE = 2,
} ComAqwertianFingeringQwertyMapper_Algorithm;

@interface ComAqwertianFingeringQwertyMapper_AlgorithmEnum : JavaLangEnum < NSCopying > {
}
+ (ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)RANDOM;
+ (ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)ROUND_ROBIN;
+ (ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)USAGE;
+ (IOSObjectArray *)values;
+ (ComAqwertianFingeringQwertyMapper_AlgorithmEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

typedef enum {
  ComAqwertianFingeringQwertyMapper_LevelOfDifficulty_BEGINNER = 0,
  ComAqwertianFingeringQwertyMapper_LevelOfDifficulty_INTERMEDIATE = 1,
  ComAqwertianFingeringQwertyMapper_LevelOfDifficulty_ADVANCED = 2,
  ComAqwertianFingeringQwertyMapper_LevelOfDifficulty_EXPERT = 3,
} ComAqwertianFingeringQwertyMapper_LevelOfDifficulty;

@interface ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum : JavaLangEnum < NSCopying > {
}
+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)BEGINNER;
+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)INTERMEDIATE;
+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)ADVANCED;
+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)EXPERT;
+ (IOSObjectArray *)values;
+ (ComAqwertianFingeringQwertyMapper_LevelOfDifficultyEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
@end

@interface ComAqwertianFingeringQwertyMapper_KeyHistory : NSObject {
 @public
  JavaUtilLinkedList *_mapped_;
  JavaUtilLinkedList *_playing_;
}

@property (nonatomic, strong) JavaUtilLinkedList *_mapped;
@property (nonatomic, strong) JavaUtilLinkedList *_playing;

- (id)init;
- (void)addNoteWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n;
- (ComAqwertianFingeringMusicFile_Note *)getPrevious;
- (ComAqwertianFingeringMusicFile_Note *)findMappedNoteWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)n;
- (BOOL)isPlayingWithComAqwertianFingeringMusicFile_Note:(ComAqwertianFingeringMusicFile_Note *)note;
- (BOOL)isFingerDownWithNSString:(NSString *)nextFinger;
@end
